package titan.lightbatis.sample.model.entity;

import javax.persistence.*;

import titan.lightbatis.annotations.DalEntity;

import javax.annotation.Generated;

import lombok.Data;
import io.swagger.annotations.ApiModel;
import titan.lightbatis.annotations.AutoGenerated;
import titan.lightbatis.annotations.Revision;
import io.swagger.annotations.ApiModelProperty;
import titan.lightbatis.annotations.LogicDelete;

/**
 * Member企业表
 */
@Table(name="member")
@Entity(name="member")
@ApiModel(value="企业表", description="企业表")
@DalEntity(name="Member", table="member")
@Generated("titan.lightbatis.web.generate.LombokBeanSerializer")
@Data
public class Member {

    @ApiModelProperty(value="创建人", allowEmptyValue=true)
    @Column(name="created_by", length=19)
    private Long createdBy;

    @AutoGenerated
    @ApiModelProperty(value="创建时间", allowEmptyValue=true)
    @Column(name="created_time", length=29)
    private java.sql.Timestamp createdTime;

    @Id
    @ApiModelProperty(value="ID", allowEmptyValue=true)
    @Column(name="id", length=19, nullable=false)
    @GeneratedValue(generator="JDBC")
    private Long id;

    @ApiModelProperty(value="企业类型", allowEmptyValue=true)
    @Column(name="kind_id", length=10)
    private Integer kindId;

    @ApiModelProperty(value="企业名称", allowEmptyValue=true)
    @Column(name="member_name", length=128)
    private String memberName;

    @ApiModelProperty(value="乐观锁", allowEmptyValue=true)
    @Column(name="revision", length=10)
    @Revision
    private Integer revision;

    @ApiModelProperty(value="企业联系人", allowEmptyValue=true)
    @Column(name="staff_id", length=19)
    private Long staffId;

    @ApiModelProperty(value="企业联系人名称", allowEmptyValue=true)
    @Column(name="staff_name", length=32)
    private String staffName;

    @LogicDelete
    @ApiModelProperty(value="数据状态，逻辑删除字段 1 = 删除， 0 = 没有删除", allowEmptyValue=true)
    @Column(name="status", length=10)
    private Integer status;

    @ApiModelProperty(value="更新人", allowEmptyValue=true)
    @Column(name="updated_by", length=19)
    private Long updatedBy;

    @AutoGenerated(event=titan.lightbatis.annotations.GeneratedEvent.Update)
    @ApiModelProperty(value="更新时间", allowEmptyValue=true)
    @Column(name="updated_time", length=29)
    private java.sql.Timestamp updatedTime;

    @ApiModelProperty(value="企业审核状态", allowEmptyValue=true)
    @Column(name="verify_status", length=32)
    private String verifyStatus;

}

