package titan.lightbatis.annotations;

import titan.lightbatis.generator.ILightbatisGenerator;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;

/**
 * @author lifei
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(FIELD)
public @interface AutoGenerated {

    /**
     * 触发自动生成的事件类型。
     * @return
     */
    GeneratedEvent event() default GeneratedEvent.Insert;

    /**
     * 生成器对应于 Spring 里的服务名称。{@link ILightbatisGenerator}, 如果为空，将根据类型自动来推荐。
     * 如：类型是 Time 将默认生成当前的时间。
     * @return
     */
    String value() default "";

}

